language: node_js
node_js:
  - "6"
install:
  - npm install
  - npm install typings -g
  - typings install
script:
  - npm test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js